### ISSUE TITLE
Translation of days is not implemented

### ISSUE THREAD

**Issue by forresst** [kanboard/plugin-timetable#1]
## Problem

As you can see from the screenshot french, the translation of days is not implemented.
Monday should be translated into Lundi.
Tuesday should be translated into Mardi
Etc ...

![kanboard_traduction](https://cloud.githubusercontent.com/assets/163352/10813512/fff717b2-7e1f-11e5-8df1-bd62fa9b6609.png)

## Currently

1. The display of the day in the table is done with the call of the function [`getWeekDay()`](https://github.com/kanboard/plugin-timetable/blob/master/Template/timetable_week/index.php#L16) in the plugin template [ plugin-timetable/Template/timetable_week/index.php](https://github.com/kanboard/plugin-timetable/blob/master/Template/timetable_week/index.php)

    ```php
    <tr>
        <td><?= $this->dt->getWeekDay($slot['day']) ?></td>
        <td><?= $slot['start'] ?></td>
        <td><?= $slot['end'] ?></td>
        <td>
            <?= $this->url->link(t('Remove'), 'timetableweek', 'confirm', array('plugin' => 'timetable', 'user_id' => $user['id'], 'slot_id' => $slot['id'])) ?>
        </td>
    </tr>
    ```

2. The display of days of the select is done with the call of the function [`getWeekDays()`](https://github.com/kanboard/plugin-timetable/blob/master/Template/timetable_week/index.php#L35) in the same template as the 1.

    ```php
<form method="post" action="<?= $this->url->href('timetableweek', 'save', array('plugin' => 'timetable', 'user_id' => $user['id'])) ?>" autocomplete="off">

    <?= $this->form->hidden('user_id', $values) ?>
    <?= $this->form->csrf() ?>

    <?= $this->form->label(t('Day'), 'day') ?>
    <?= $this->form->select('day', $this->dt->getWeekDays(), $values, $errors) ?>

    <?= $this->form->label(t('Start time'), 'start') ?>
    <?= $this->form->select('start', $this->dt->getDayHours(), $values, $errors) ?>

    <?= $this->form->label(t('End time'), 'end') ?>
    <?= $this->form->select('end', $this->dt->getDayHours(), $values, $errors) ?>

    <div class="form-actions">
        <input type="submit" value="<?= t('Save') ?>" class="btn btn-blue"/>
    </div>
</form>
    ```

`getWeekDay()` and `getWeekDays()` are defined in the file Kanboard [Dt.php](https://github.com/fguillot/kanboard/blob/master/app/Helper/Dt.php). Note: `getWeekDays()` run the getWeekDay() function :

```php
    /**
     * Get all days of a week
     *
     * @access public
     * @return array
     */
    public function getWeekDays()
    {
        $values = array();
        foreach (range(1, 7) as $day) {
            $values[$day] = $this->getWeekDay($day);
        }
        return $values;
    }
    /**
     * Get the localized day name from the day number
     *
     * @access public
     * @param  integer   $day  Day number
     * @return string
     */
    public function getWeekDay($day)
    {
        return dt('%A', strtotime('next Monday +'.($day - 1).' days'));
    }
```

## Proposed solution

Although `getWeekDay()` and `getWeekDays()` are only executed in this plugin, it must translate into being thanks to the function t (). It must be replaced:
```php
        return dt('%A', strtotime('next Monday +'.($day - 1).' days'));
```
By :
```php
        return t(dt('%A', strtotime('next Monday +'.($day - 1).' days')));
```
And of course add translations in locale files (for example [locale french](https://github.com/fguillot/kanboard/blob/master/app/Locale/fr_FR/translations.php)) :

```php
    'Monday' => 'Lundi',
    'Tuesday' => 'Mardi',
    'Wednesday' => 'Mercredi',
    'Thursday' => 'Jeudi',
    'Friday' => 'Vendredi',
    'Saturday' => 'Samedi',
    'Sunday' => 'Dimanche',
```

What do you think ? If the solution suits you, I can do the PR.

**Comment by fguillot** [comment]
The localization of date and time are using the function `strftime()` that rely on the installed locales on the system. To see days in French, you need to have the french locale installed on your server:

```bash
locale -a | grep fr_FR
fr_FR
fr_FR.iso88591
fr_FR.utf8
```

If you are using Debian/Ubuntu, you can do `locale-gem fr_FR` and `locale-gen fr_FR.UTF-8`, reload the php process if necessary and you should see the day in French.
